version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
    groups:
      react: { patterns: ["react", "react-dom", "@types/react", "@types/react-dom"] }
      next: { patterns: ["next", "@next/*", "@serwist/*", "serwist"] }
      types: { patterns: ["@types/*"] }
      leaflet: { patterns: ["leaflet", "leaflet-*", "react-leaflet*", "@types/leaflet"] }
    labels: ["dependencies"]
